'use client'
// import type { Metadata } from 'next'

import { Inter } from 'next/font/google'
import './globals.css'
import { ApolloClient, InMemoryCache, ApolloProvider } from '@apollo/client'
import { PaymentProvider } from '@/components/contexts/checkContext'
import { Toaster } from 'sonner';
import { NextUIProvider } from "@nextui-org/react";

const inter = Inter({ subsets: ['latin'] })

const graphqlClient = new ApolloClient({
  uri: "http://localhost:8000/graphql",
  cache: new InMemoryCache()
});

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloProvider client={graphqlClient}>
          <NextUIProvider>
            <PaymentProvider>
              {children}
            </PaymentProvider>
          </NextUIProvider>
          <Toaster richColors position="top-right" />
        </ApolloProvider>
      </body>
    </html>
  )
}
